### ISSUE TITLE
Support Elasticsearch 5.x

### ISSUE THREAD

**Issue by faxm0dem** [gigya/kibana#16]
I started looking at what has to be done.
The things I already found:

* GET `search_type=count` needs to be replaced with `search_type=query_then_fetch`
* POST data `ignore_unmapped` must be removed or replaced with `unmapped_type` [See ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields)
* POST `filtered` queries are deprecated and need to be replaced with `bool/must/filter` [See stackoverflow](http://stackoverflow.com/questions/40519806/no-query-registered-for-filtered)
* See [grafana diff](https://github.com/grafana/grafana/pull/4970/files) for other things maybe

**Comment by CpuID** [comment]
Most of this looks to be in the underlying [elastic.js](https://github.com/fullscale/elastic.js) vendored library. No updates since 2014, and [one of the forks](https://github.com/ErwanPigneul/elastic.js) claims the DSL changed too much in 5.x to be compatible.

One suggestion is https://github.com/sudo-suhas/elastic-builder but who knows if that would be more of a "starting again" replacement.

**Comment by ekutner** [comment]
Elastic 5 and 6 are now supported

**Comment by CpuID** [comment]
> Elastic 5 and 6 are now supported

oooo thx
